[package]
name = "univie-report-template-typst-unofficial"
version = "0.1.0"
entrypoint = ""
authors = ["Nayeli Gast Zepeda <nayeli.gast.zepeda@univie.ac.at>", "Xiaowei Liu <ddvlau@foxmail.com>"]
license = "MIT"
description = "Unofficial typst template for Uni Vienna Report"
repository = ""
keywords = [""]
categories = [""]
compiler = "0.14.2"